apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    platformctl.lab: redis-cluster
  ports:
    - name: redis
      port: 6379
    - name: bus
      port: 16379
